# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "peach"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# https://www.pgpool.net/docs/4.2.2/en/html/runtime-config-connection-pooling.html#runtime-config-connection-pooling-pool-mode
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: 0.0.0.0)
bind_address = "0.0.0.0"
# Port to use for the local Realtime API.
port = 54323

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = true
# Template for sending a confirmation message when the user signs up with a phone number.
template = "Your code is {{ .Code }}"

# Use pre-defined map of phone number to OTP for testing.
# [auth.sms.test_otp]
# 1234567890 = "123456"

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
# [auth.sms.twilio]
# enabled = true
# account_sid = "AC1234567890abcdef1234567890abcdef"
# message_service_sid = "MG1234567890abcdef1234567890abcdef"
# # DO NOT commit the real auth_token to Git history, use environment variable substitution instead.
# auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"
# # Override the default Twilio API endpoint (e.g. for testing)
# api_base_url = "https://api.twilio.com"

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = true
# client_id = "env(SUPABASE_AUTH_EXTERNAL_APPLE_CLIENT_ID)"
# # DO NOT commit the real client_secret to Git history, use environment variable substitution instead.
# secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
# # Override the default OAuth redirect URL (e.g. for testing)
# redirect_uri = "http://localhost:9999/auth/v1/callback"

[edge_functions]
enabled = true
# Configure one of the supported import map providers: `bundler`, `native`.
# `bundler` - use Deno's import map support with bundling (default).
# `native` - use Deno's native import map support without bundling.
import_map_provider = "bundler"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"
